/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Lox.app;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class MessageUtilsTest {
    @Test void testGetMessage() {
        assertEquals(true, true); // A stub for a test
    }
}
